### ISSUE TITLE
SSDMobilenet Confidence is always zero

### ISSUE THREAD

**Issue by ghost** [fdchiu/SNPECam#2]
Hello, 

I tried your app but the confidence always stays zero. Do you have any suggestion ?

**Comment by senthilnathansss** [comment]
I also got into the same issue.  Any luck with you on this?

**Comment by ghost** [comment]
You can visit https://github.com/SimranMarok for the solution. I have developed Android App and two models which are able to achieve 99% miou @ 11fps (513x513 input) and 90% miou @ 30fps (256x256 input).
